# Generated by Django 3.0.6 on 2020-05-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='questions',
            field=models.ManyToManyField(to='listings.Question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback',
            field=models.ManyToManyField(to='listings.Review'),
        ),
        migrations.AlterField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(to='listings.Listing'),
        ),
    ]
