# Generated by Django 3.0.6 on 2020-05-13 14:52

from django.db import migrations
import listings.managers


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', listings.managers.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='author',
            new_name='owner',
        ),
    ]
