# Generated by Django 3.0.6 on 2020-05-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200510_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created']},
        ),
    ]
