# Generated by Django 3.0.6 on 2020-05-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200514_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
