# Generated by Django 3.0.6 on 2020-05-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_question_seller'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'target')},
        ),
    ]
