# Generated by Django 3.0.7 on 2020-06-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200519_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('VEHICLES', 'vehicles'), ('ELECTRONICS', 'electronics'), ('HOME', 'home'), ('CLOTHES', 'clothes'), ('FURNITURE', 'furniture')], max_length=11),
        ),
    ]
