# Generated by Django 3.0.7 on 2020-06-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('VEHICLES', 'vehicles'), ('CARS', 'cars'), ('MOTORCYCLES', 'motorcycles'), ('BICYCLES', 'bicycles'), ('ELECTRONICS', 'electronics'), ('COMPUTERS', 'computers'), ('SMARTPHONES', 'smartphones'), ('SMARTDEVICES', 'smartdevices'), ('PERIPHERALS', 'peripherals'), ('TELEVISIONS', 'televisions'), ('HOME', 'home'), ('APPLIANCES', 'appliances'), ('FURNITURE', 'furniture'), ('KITCHEN', 'kitchen'), ('CLOTHES', 'clothes'), ('SHOES', 'shoes'), ('PANTS', 'pants'), ('SHIRTS', 'shirts'), ('JACKETS', 'jackets'), ('HATS', 'hats')], max_length=13),
        ),
    ]
