# Generated by Django 3.0.7 on 2020-06-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
