# Generated by Django 3.0.7 on 2020-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
