# Generated by Django 3.0.7 on 2020-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CARS', 'cars'), ('MOTORCYCLES', 'motorcycles'), ('BICYCLES', 'bicycles'), ('COMPUTERS', 'computers'), ('SMARTPHONES', 'smartphones'), ('SMARTDEVICES', 'smartdevices'), ('PERIPHERALS', 'peripherals'), ('TELEVISIONS', 'televisions'), ('APPLIANCES', 'appliances'), ('FURNITURE', 'furniture'), ('KITCHEN', 'kitchen'), ('SHOES', 'shoes'), ('PANTS', 'pants'), ('SHIRTS', 'shirts'), ('JACKETS', 'jackets'), ('HATS', 'hats'), ('OTHER', 'other')], default='OTHER', max_length=13),
        ),
    ]
